<a href="https://colab.research.google.com/github/MichalRozenwald/epiCausality/blob/main/MethBank_generating_mC_vectors_for_ROI_from_bedgraph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np


In [ ]:
bedgraph_path = "/content/Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2-chr1-207320824..207320905.bedgraph"

# Read the BedGraph File: Use Python's built-in file handling methods to read the .bedgraph file. Here’s how you might start:
with open(bedgraph_path, 'r') as file:
    bedgraph_data = file.readlines()


In [ ]:
# Process Data with Pandas: Import the Pandas library to manage and analyze your data effectively. You can convert your data into a DataFrame for easier manipulation:
bedgraph_df = pd.read_csv(bedgraph_path, sep='\t', header=None, names=['chrom', 'start', 'end', 'value'])
bedgraph_df

chrom        start  \
0   track type=bedGraph name="Homo_sapiens_watson_...          NaN   
1                                                 NaN  207320824.0   
2                                                 NaN  207320826.0   
3                                                 NaN  207320831.0   
4                                                 NaN  207320832.0   
5                                                 NaN  207320833.0   
6                                                 NaN  207320834.0   
7                                                 NaN  207320838.0   
8                                                 NaN  207320842.0   
9                                                 NaN  207320851.0   
10                                                NaN  207320869.0   
11                                                NaN  207320874.0   
12                                                NaN  207320876.0   
13                                                NaN  207320877.0   
14                                                NaN  207320879.0   
15                                                NaN  207320881.0   
16                                                NaN  207320883.0   
17                                                NaN  207320885.0   
18                                                NaN  207320887.0   
19                                                NaN  207320889.0   
20                                                NaN  207320891.0   
21                                                NaN  207320893.0   

            end     value  
0           NaN       NaN  
1   207320825.0  0.040000  
2   207320827.0  0.653846  
3   207320832.0  0.000000  
4   207320833.0  0.000000  
5   207320834.0  0.000000  
6   207320835.0  0.000000  
7   207320839.0  0.000000  
8   207320843.0  0.000000  
9   207320852.0  0.000000  
10  207320870.0  1.000000  
11  207320875.0  0.666667  
12  207320877.0  0.050000  
13  207320878.0  0.000000  
14  207320880.0  0.900000  
15  207320882.0  0.952381  
16  207320884.0  0.947368  
17  207320886.0  0.952381  
18  207320888.0  0.952381  
19  207320890.0  0.900000  
20  207320892.0  0.894737  
21  207320894.0  0.411765

In [ ]:
bedgraph_df.iloc[0]['chrom']

'track type=bedGraph name="Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2" description="Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2"'

In [ ]:
# Subset the Data: Assuming you need to focus on specific regions or samples, you can subset the DataFrame:

# subset_df = bedgraph_df[(bedgraph_df['chrom'] == 'chr1') & (bedgraph_df['start'] >= 207320867) & (bedgraph_df['end'] <= 207320897)]
subset_df = bedgraph_df[(bedgraph_df['start'] >= 207320867) & (bedgraph_df['end'] <= 207320897)]
subset_df

chrom        start          end     value
10   NaN  207320869.0  207320870.0  1.000000
11   NaN  207320874.0  207320875.0  0.666667
12   NaN  207320876.0  207320877.0  0.050000
13   NaN  207320877.0  207320878.0  0.000000
14   NaN  207320879.0  207320880.0  0.900000
15   NaN  207320881.0  207320882.0  0.952381
16   NaN  207320883.0  207320884.0  0.947368
17   NaN  207320885.0  207320886.0  0.952381
18   NaN  207320887.0  207320888.0  0.952381
19   NaN  207320889.0  207320890.0  0.900000
20   NaN  207320891.0  207320892.0  0.894737
21   NaN  207320893.0  207320894.0  0.411765

In [ ]:
# Analyze the Subset: Perform your desired statistical analysis or data visualization on the subset. For example, to summarize methylation levels:
average_methylation = subset_df['value'].mean()
print(f'Average Methylation: {average_methylation}')


Average Methylation: 0.7189732904856404


In [ ]:
# Additional Tools: For more complex analyses, consider using bioinformatics libraries such as Biopython or Pybedtools, which offer extensive functionalities for handling genomic data.


In [ ]:
# Extract the Column as a Series: If bedgraph_df is your DataFrame and you are interested in converting the 'value' column (which typically holds the methylation value or other genomic data), you can do it like this:

values_series = subset_df['value']
# Convert the Series To Numpy Array: For a Numpy array, which is more suitable for numerical operations and is commonly used in scientific computing, use:

values_array = values_series.to_numpy()
values_array

array([1.        , 0.66666669, 0.05      , 0.        , 0.89999998,
       0.95238096, 0.94736844, 0.95238096, 0.95238096, 0.89999998,
       0.89473683, 0.41176471])

In [ ]:
len(values_array)

12

In [ ]:

start_values = subset_df['start']
start_values = start_values.to_numpy()
start_values

array([2.07320869e+08, 2.07320874e+08, 2.07320876e+08, 2.07320877e+08,
       2.07320879e+08, 2.07320881e+08, 2.07320883e+08, 2.07320885e+08,
       2.07320887e+08, 2.07320889e+08, 2.07320891e+08, 2.07320893e+08])

# Coordinates of the C (in the CG units) in my Region of Interest (ROI)

In Reference genome: GRCh38/hg38

In the FORWARD Strand:

1. 207,320,868
2. 207,320,873
3. 207,320,878
4. 207,320,880
5. 207,320,882
6. 207,320,884
7. 207,320,886
8. 207,320,888
9. 207,320,890
10. 207,320,892



In [ ]:
C_CG_coords = [
    207320868,
    207320873,
    207320878,
    207320880,
    207320882,
    207320884,
    207320886,
    207320888,
    207320890,
    207320892
]
len(C_CG_coords), C_CG_coords

(10,
 [207320868,
  207320873,
  207320878,
  207320880,
  207320882,
  207320884,
  207320886,
  207320888,
  207320890,
  207320892])

In [19]:
import pandas as pd
import numpy as np

In [ ]:
bedgraph_path = "/content/Homo_sapiens_crick_CG_HepG2_HepatocellularCarcinoma_15yrs_Male_child_Rep1-chr1-207320821..207320911.bedgraph"
# "/content/Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2-chr1-207320824..207320905.bedgraph"

# Read the BedGraph File: Use Python's built-in file handling methods to read the .bedgraph file. Here’s how you might start:
with open(bedgraph_path, 'r') as file:
    bedgraph_data = file.readlines()

# Process Data with Pandas: Import the Pandas library to manage and analyze your data effectively. You can convert your data into a DataFrame for easier manipulation:
bedgraph_df = pd.read_csv(bedgraph_path, sep='\t', header=None, names=['chrom', 'start', 'end', 'value'])
bedgraph_df

chrom        start  \
0   track type=bedGraph name="Homo_sapiens_crick_C...          NaN   
1                                                 NaN  207320825.0   
2                                                 NaN  207320868.0   
3                                                 NaN  207320873.0   
4                                                 NaN  207320878.0   
5                                                 NaN  207320880.0   
6                                                 NaN  207320882.0   
7                                                 NaN  207320884.0   
8                                                 NaN  207320886.0   
9                                                 NaN  207320888.0   
10                                                NaN  207320890.0   
11                                                NaN  207320892.0   

            end     value  
0           NaN       NaN  
1   207320826.0  0.857143  
2   207320869.0  0.750000  
3   207320874.0  1.000000  
4   207320879.0  1.000000  
5   207320881.0  0.750000  
6   207320883.0  1.000000  
7   207320885.0  1.000000  
8   207320887.0  1.000000  
9   207320889.0  1.000000  
10  207320891.0  1.000000  
11  207320893.0  0.333333

In [10]:
# unordered [C_coord in C_CG_coords for C_coord in bedgraph_df['start']]

In [12]:
selected_C_values = bedgraph_df[bedgraph_df['start'].isin(C_CG_coords)]
selected_C_values

chrom        start          end     value
2    NaN  207320868.0  207320869.0  0.750000
3    NaN  207320873.0  207320874.0  1.000000
4    NaN  207320878.0  207320879.0  1.000000
5    NaN  207320880.0  207320881.0  0.750000
6    NaN  207320882.0  207320883.0  1.000000
7    NaN  207320884.0  207320885.0  1.000000
8    NaN  207320886.0  207320887.0  1.000000
9    NaN  207320888.0  207320889.0  1.000000
10   NaN  207320890.0  207320891.0  1.000000
11   NaN  207320892.0  207320893.0  0.333333

In [15]:
selected_C_values = selected_C_values.sort_values(by=['start'], ascending=True)
selected_C_values

chrom        start          end     value
2    NaN  207320868.0  207320869.0  0.750000
3    NaN  207320873.0  207320874.0  1.000000
4    NaN  207320878.0  207320879.0  1.000000
5    NaN  207320880.0  207320881.0  0.750000
6    NaN  207320882.0  207320883.0  1.000000
7    NaN  207320884.0  207320885.0  1.000000
8    NaN  207320886.0  207320887.0  1.000000
9    NaN  207320888.0  207320889.0  1.000000
10   NaN  207320890.0  207320891.0  1.000000
11   NaN  207320892.0  207320893.0  0.333333

In [24]:
# Make sure that the order of the values is correct (aligned with the order set in 'C_CG_coords')
sum(np.array(selected_C_values['start']) != np.array(C_CG_coords)) == 0

True

In [32]:
mC_probs_per_position_HepG2 = list(selected_C_values['value'])
mC_probs_per_position_HepG2

[0.75, 1.0, 1.0, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3333333432674408]

# For the Pancreas data:

In [47]:

bedgraph_path = "/content/Homo_sapiens_crick_CG_Pancreas_37yrs_Male-chr1-207320821..207320911.bedgraph"
# "/content/Homo_sapiens_crick_CG_HepG2_HepatocellularCarcinoma_15yrs_Male_child_Rep1-chr1-207320821..207320911.bedgraph"
# "/content/Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2-chr1-207320824..207320905.bedgraph"

# Read the BedGraph File: Use Python's built-in file handling methods to read the .bedgraph file. Here’s how you might start:
with open(bedgraph_path, 'r') as file:
    bedgraph_data = file.readlines()

# Process Data with Pandas: Import the Pandas library to manage and analyze your data effectively. You can convert your data into a DataFrame for easier manipulation:
bedgraph_df = pd.read_csv(bedgraph_path, sep='\t', header=None, names=['chrom', 'start', 'end', 'value'])
bedgraph_df

# Select the C positions of interest identified in the 'C_CG_coords' vector
selected_C_values = bedgraph_df[bedgraph_df['start'].isin(C_CG_coords)]
selected_C_values = selected_C_values.sort_values(by=['start'], ascending=True)

# Make sure that the order of the values is correct (aligned with the order set in 'C_CG_coords')
has_all_sorted_Cs =sum(np.array(selected_C_values['start']) != np.array(C_CG_coords)) == 0
print("Check that the values in the extracted mC vector are exactly the same as the ones identified in the Cs position list", has_all_sorted_Cs)

mC_probs_per_position = list(selected_C_values['value'])
mC_probs_per_position

Check that the values in the extracted mC vector are exactly the same as the ones identified in the Cs position list True


[0.4285714328289032,
 0.4285714328289032,
 0.6666666865348816,
 0.3333333432674408,
 0.5,
 0.3333333432674408,
 0.2000000029802322,
 0.0,
 0.3333333432674408,
 0.0]

In [48]:
np.around(mC_probs_per_position, decimals=2, out=None)

array([0.43, 0.43, 0.67, 0.33, 0.5 , 0.33, 0.2 , 0.  , 0.33, 0.  ])

In [49]:
len(mC_probs_per_position)

10

# lymphoblast cell line
- that is aligned with the Nanopore data from the Pangenome dataset  (HG00408 individual als have lymphoblast cells)


## This data if for the reverse strand

In [42]:
C_CG_coords

[207320868,
 207320873,
 207320878,
 207320880,
 207320882,
 207320884,
 207320886,
 207320888,
 207320890,
 207320892]

In [63]:
C_CG_coords_fwd=np.array(C_CG_coords)

def extract_mC_probs_from_BS_bedgraph(bedgraph_path, is_forward_strand,
                                      C_CG_coords_fwd=[207320868,207320873,207320878,207320880,207320882,207320884,207320886,207320888,207320890,207320892]
                                      ):
  # For the data from the Reverese strand: Shift by one the coordinates of the C locations
  if is_forward_strand == False:
    C_CG_coords_fwd += 1
    print("This file is from the Reverse strand, so shifting the C coordinates by one")
    print(C_CG_coords_fwd)

  # Read the BedGraph File: Use Python's built-in file handling methods to read the .bedgraph file. Here’s how you might start:
  with open(bedgraph_path, 'r') as file:
      bedgraph_data = file.readlines()

  # Process Data with Pandas: Import the Pandas library to manage and analyze your data effectively. You can convert your data into a DataFrame for easier manipulation:
  bedgraph_df = pd.read_csv(bedgraph_path, sep='\t', header=None, names=['chrom', 'start', 'end', 'value'])
  bedgraph_df

  # Select the C positions of interest identified in the 'C_CG_coords' vector
  selected_C_values = bedgraph_df[bedgraph_df['start'].isin(C_CG_coords_fwd)]
  selected_C_values = selected_C_values.sort_values(by=['start'], ascending=True)

  # Make sure that the order of the values is correct (aligned with the order set in 'C_CG_coords_fwd')
  has_all_sorted_Cs =sum(np.array(selected_C_values['start']) != np.array(C_CG_coords_fwd)) == 0
  print("Check that the values in the extracted mC vector are exactly the same as the ones identified in the Cs position list", has_all_sorted_Cs)

  mC_probs_per_position = list(selected_C_values['value'])
  print(mC_probs_per_position)
  return(mC_probs_per_position)


In [65]:
bedgraph_path = "/content/Homo_sapiens_watson_CG_Cancer_Lymphoblastoid_SUB33-chr1-207320817..207320907.bedgraph"
is_forward_strand = False

extract_mC_probs_from_BS_bedgraph(bedgraph_path, is_forward_strand,
                                      C_CG_coords_fwd=np.array(C_CG_coords))


# "/content/Homo_sapiens_crick_CG_Pancreas_37yrs_Male-chr1-207320821..207320911.bedgraph"
# "/content/Homo_sapiens_crick_CG_HepG2_HepatocellularCarcinoma_15yrs_Male_child_Rep1-chr1-207320821..207320911.bedgraph"
# "/content/Homo_sapiens_watson_C_Tumor_HepG2_15yrs_Male_Rep2-chr1-207320824..207320905.bedgraph"

This file is from the Reverse strand, so shifting the C coordinates by one
[207320869 207320874 207320879 207320881 207320883 207320885 207320887
 207320889 207320891 207320893]
Check that the values in the extracted mC vector are exactly the same as the ones identified in the Cs position list True
[0.5, 0.0, 0.25, 0.25, 0.25, 0.25, 0.5, 0.25, 0.0, 0.0]


[0.5, 0.0, 0.25, 0.25, 0.25, 0.25, 0.5, 0.25, 0.0, 0.0]

In [66]:
C_CG_coords

[207320868,
 207320873,
 207320878,
 207320880,
 207320882,
 207320884,
 207320886,
 207320888,
 207320890,
 207320892]

In [67]:
bedgraph_df

chrom        start  \
0   track type=bedGraph name="Homo_sapiens_watson_...          NaN   
1                                                 NaN  207320826.0   
2                                                 NaN  207320869.0   
3                                                 NaN  207320874.0   
4                                                 NaN  207320879.0   
5                                                 NaN  207320881.0   
6                                                 NaN  207320883.0   
7                                                 NaN  207320885.0   
8                                                 NaN  207320887.0   
9                                                 NaN  207320889.0   
10                                                NaN  207320891.0   
11                                                NaN  207320893.0   

            end     value  
0           NaN       NaN  
1   207320827.0  0.142857  
2   207320870.0  0.500000  
3   207320875.0  0.000000  
4   207320880.0  0.250000  
5   207320882.0  0.250000  
6   207320884.0  0.250000  
7   207320886.0  0.250000  
8   207320888.0  0.500000  
9   207320890.0  0.250000  
10  207320892.0  0.000000  
11  207320894.0  0.000000

# Sampling single reads:


In [36]:
# Sampling single reads:

mC_probs_per_position = mC_probs_per_position_HepG2

N_SAMPLES = 10

for P_methylated in mC_probs_per_position:
    print(np.random.choice(2, size=N_SAMPLES, replace=True, p=[1-P_methylated, P_methylated]))

[1 1 1 1 1 0 0 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 0 1 1 1 0 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[0 0 1 1 0 1 1 1 0 0]
