# Build ML models

In [1]:
# ! python3 -m pip install 'scikit-learn'

In [13]:
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import *
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.svm import SVC, SVR
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.model_selection import train_test_split

import numpy as np
import time

import sklearn

# import shap


ModuleNotFoundError: No module named 'shap'

In [3]:
# From /home/michalula/code/epiCausality/epiCode/PIPELINE_extract_plot_mCG_strands_profiles_bigger_window.ipynb
# CGs_all saved as CG_combined_silenced_T_primerES_nCATS_numFWD3852_numRVS2805_padded_reads_silenced_T_primerES_nCATS_mCthresh0.9_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy in dimelo_v2_output
# Pipeline executed successfully (analize_forward_reverse_CGs_pipeline function)

In [4]:
CGs_all_silenced = np.load('/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_silenced_T_primerES_nCATS_numFWD3852_numRVS2805_padded_reads_silenced_T_primerES_nCATS_mCthresh0.9_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy')
# Silenced T cells nCATS:
# Threshold 0.7 = ("/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_silenced_T_primerES_nCATS_numFWD4132_numRVS2965_padded_reads_silenced_T_primerES_nCATS_mCthresh0.7_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy")
# # Threshold 0.9 =( '/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_silenced_T_primerES_nCATS_numFWD3852_numRVS2805_padded_reads_silenced_T_primerES_nCATS_mCthresh0.9_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy')

CGs_all_silenced, CGs_all_silenced.shape

(array([[nan, nan, nan, ..., nan, nan,  1.],
        [nan, nan,  1., ..., nan, nan, nan],
        [nan, nan,  1., ..., nan, nan,  1.],
        ...,
        [nan, nan, nan, ...,  1., nan,  1.],
        [nan, nan, nan, ...,  1.,  1., nan],
        [nan, nan, nan, ..., nan,  1., nan]]),
 (6657, 10))

In [5]:
# Undetided T cells nCATS get lable 0 as CD55 is lowly expressed in silened T cells (~90% of cells should be silenced)
y_silenced = np.array([0] * CGs_all_silenced.shape[0])
y_silenced, y_silenced.shape

(array([0, 0, 0, ..., 0, 0, 0]), (6657,))

In [6]:
CGs_all_unedited = np.load("/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_unedited_T_primerES_nCATS_numFWD788_numRVS516_padded_reads_unedited_T_primerES_nCATS_mCthresh0.9_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy")

# Unedited T cells nCATS:
# Threshold 0.7 =  ("/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_unedited_T_primerES_nCATS_numFWD1081_numRVS662_padded_reads_unedited_T_primerES_nCATS_mCthresh0.7_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy")
# Threshold 0.9 =("/home/michalula/code/epiCausality/epiCode/dimelo_v2_output/CG_combined_unedited_T_primerES_nCATS_numFWD788_numRVS516_padded_reads_unedited_T_primerES_nCATS_mCthresh0.9_t2t_v1_1_chr1:206586162-206586192_2025-02-03.npy")

CGs_all_unedited, CGs_all_unedited.shape

(array([[nan, nan,  1., ..., nan, nan,  1.],
        [ 1.,  1.,  1., ...,  1., nan, nan],
        [ 1., nan,  1., ...,  1., nan, nan],
        ...,
        [nan,  1., nan, ...,  1., nan, nan],
        [ 1., nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ...,  1., nan, nan]]),
 (1304, 10))

In [7]:
# Undetided T cells nCATS get lable 1 as CD55 is highly expressed in undetided T cells
y_unedited = np.array([1] * CGs_all_unedited.shape[0])
y_unedited, y_unedited.shape

(array([1, 1, 1, ..., 1, 1, 1]), (1304,))

In [16]:
X_unedited_silenced = np.concatenate((CGs_all_unedited, CGs_all_silenced), axis=0)
X_unedited_silenced

array([[nan, nan,  1., ..., nan, nan,  1.],
       [ 1.,  1.,  1., ...,  1., nan, nan],
       [ 1., nan,  1., ...,  1., nan, nan],
       ...,
       [nan, nan, nan, ...,  1., nan,  1.],
       [nan, nan, nan, ...,  1.,  1., nan],
       [nan, nan, nan, ..., nan,  1., nan]])

In [15]:

train_idx, test_idx = train_test_split(np.arange(y_unedited.shape[0]), train_size=.75, random_state=16)
train_idx, test_idx

(array([  67,  120,  785,  110,  845,  343,  750,  542, 1266,  324, 1002,
        1122,  118,  735,   20,  525,  327,  637,  392,   55,  790, 1193,
         864,  866,  141,   78, 1115,  792, 1041,   43,  854, 1228,  131,
          34, 1289,  939, 1245,  301,  398,  865, 1006,  974,  947,   48,
         400,  490,  514,  685, 1015,  284,  311,  781,  951,  297,  550,
         403, 1183,  300,  566,  164,  762, 1020,  900, 1299,  235,  667,
         923,  171,  651,  500,  532,  386,  828,   77, 1133,  763,  608,
         996,  991,  734,  840, 1188,  988,  211,  181, 1060,  863,  265,
         315, 1030,  476,  904, 1101,  458,  999,  663, 1116, 1149,  192,
         273,  270,  628, 1077,  445, 1185,   26,  201,  757,   86,   97,
         388,  956,  908, 1284,  468,  140,  250,  459,  700,  283,  633,
         295,  704, 1058, 1229,  639, 1021,  835,  889, 1205,  551,  229,
         154,  144,  992, 1226,    9,  466,  541, 1287,  530, 1243,  954,
         557,  396,  336,  720, 1275, 

In [ ]:

X_train, X_test, Y_train, Y_test = train_test_split(
    *shap.datasets.iris(), test_size=0.2, random_state=0
)


In [ ]:
Y = np.repeat([0,50,100], N_SAMPLES)
X_train, X_test = X[train_idx], X[test_idx]
Y_train, Y_test = Y[train_idx], Y[test_idx]

def predict_reg(f, X, Y):
    preds = f.predict(X)
    preds012 = np.round(preds / 50) # 100-->2; 50-->1; 0-->0
    return np.mean(preds012*50==Y)*100

model = LinearRegression().fit(X_train,Y_train)
print("GLM: {:.2f}%".format(predict_reg(model, X_test, Y_test)))

print("####")
model = DecisionTreeRegressor().fit(X_train,Y_train)
print("Tree: {:.2f}%".format(predict_reg(model, X_test, Y_test)))
print("####")
model = RandomForestRegressor().fit(X_train,Y_train)
print("RF: {:.2f}%".format(predict_reg(model, X_test, Y_test)))
print("####")
model = GradientBoostingRegressor().fit(X_train,Y_train)
print("GBM: {:.2f}%".format(predict_reg(model, X_test, Y_test)))
print("####")
model = MLPRegressor(max_iter=1000,hidden_layer_sizes=(50,20)).fit(X_train, Y_train)
print("NN: {:.2f}%".format(predict_reg(model, X_test, Y_test)))